config/routes.rb
WeddingFrontend::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users do
    resources :weddings do
      resources :items
    end
  end

  resources :items
  resources :pins
  resources :honeymoons
  resources :pages

  resources :weddings
  root to: 'pages#index'

end

app/models/wedding.rb
class Wedding < OpenStruct
  
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController

  before_filter :require_login, only: [:update, :create, :destroy]
  before_filter :set_key, only: [:edit, :update, :create, :destroy]

  def index
    weddings = if params[:user_id]
      WeddingRequest.find_all(user_id: params[:user_id])
    else
      WeddingRequest.find_all.reverse
    end

    @weddings = weddings.paginate(page: params[:page], per_page: 5)

    unless @weddings.respond_to?(:each)
      flash.now[:error] = @weddings
      redirect_to root_path
    end
  end

  def show
    if current_user
      @weddings = WeddingRequest.find_all(user_id: current_user.id)
    end
    @wedding = WeddingRequest.find(params[:id])
    @items =  ItemRequest.find_all_by_wedding(@wedding.id)
  end

  def new
  end

  def create
    params[:wedding][:user_id] = current_user.id
    response = WeddingRequest.create(params[:wedding], params[:api_key])
    if response.success?
      flash.now[:notice] = "Successfully created wedding!"
      redirect_to user_weddings_path(current_user.id)
    else
      flash.now[:error] = "Unable to create wedding. See errors below."
      render :new
    end
  end

  def edit
    @wedding = WeddingRequest.find(params[:id])
  end

  def update
    if params[:wedding][:user_id].to_i == current_user.id
      response = WeddingRequest.update(params[:id], params[:wedding], params[:api_key])
      if response.success?
        flash.now[:notice] = "Successfully updated wedding!"
        redirect_to wedding_path(response.parsed_response[:id])
      else
        flash.now[:notice] = "Couldn't update this wedding"
        redirect_to wedding_path(params[:wedding][:id])
      end
    else
      flash.now[:notice] = "You are not authorized to edit this wedding."
      redirect_to user_weddings_path(current_user.id)
    end
  end

  def destroy
    @wedding = WeddingRequest.find(params[:id])
    if @wedding.user_id == current_user.id
      response = WeddingRequest.destroy(params[:id], params[:api_key])
      if response.success?
        flash.now[:notice] = "Successfully deleted wedding."
        redirect_to user_weddings_path(current_user.id)
      else
        flash.now[:notice] = "Couldn't delete this wedding."
        redirect_to user_weddings_path(current_user.id)
      end
    else
      flash.now[:notice] = "You are not authorized to edit this wedding"
      redirect_to weddings_path
    end
  end
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/weddings/_add_item_bar.html.slim
.search-box
  h3 Add a new idea
  = form_tag items_path, class: "add-item-form" do
    = label_tag("[item]photo_url", "Picture URL")
    = text_field_tag("[item]photo_url")
    = label_tag("[item]description", "Description")
    = text_field_tag("[item]description")
    = hidden_field_tag("[item]wedding_id", @wedding.id)
    = submit_tag
.search-box
  h3 Search for ideas
  = form_tag(pins_path, method: "get") do
    = text_field_tag(:search)
    = submit_tag "Find"

app/views/weddings/_descriptive_wedding.html.slim
.wedding-bar
  = image_tag wedding.photo_url, style: "height: 175px"
  = link_to wedding.name, wedding_path(wedding.id), class: "title"
  p.bottom-bar
    - if current_user && @wedding.user_id == current_user.id
        = link_to "edit", "#"
    = time_ago_in_words(Time.parse(wedding.created_at)) + " ago"
  - if current_user && current_user.id == @wedding.user_id
    .wedding-details
      = form_tag wedding_path(@wedding.id), method: "put" do
        = label_tag("[wedding]name", "Wedding Plan Name")
        br
        = text_field_tag("[wedding]name", @wedding.name)
        br
        = label_tag("[wedding]photo_url", "Cover Photo")
        br
        = text_area_tag("[wedding]photo_url", @wedding.photo_url)
        br
        = label_tag("[wedding]description", "Description")
        br
        = text_area_tag("[wedding]description", @wedding.description)
        = hidden_field_tag("wedding[user_id]", @wedding.user_id)
        p
        = submit_tag
      = link_to "delete", wedding_path(@wedding.id), confirm: "Are you sure?", method: :delete

app/views/weddings/_item.html.slim
.search-box
  .image
    = image_tag item.photo_url
    - if current_user && @wedding.user_id == current_user.id
      p.description = item.description
      p.show-details
        = link_to "details", "#"
    - elsif current_user
      p.description-heart = item.description
      = link_to(image_tag('https://s3.amazonaws.com/bride-items/add-favorite.png', class: "wed-heart"), "#")
    - else
      = link_to(image_tag('https://s3.amazonaws.com/bride-items/add-favorite.png', class: "non-logged-in-heart"), signup_path(error: "Please create an account or login to save ideas!"))
    p.bottom-bar
      = time_ago_in_words(Time.parse(item.created_at)) + " ago"
    - if current_user && @wedding.user_id == current_user.id
      .details
        = form_tag item_path(item.id), method: :put do
          = hidden_field_tag("[item]wedding_id", @wedding.id)
          = hidden_field_tag("[item]photo_url", item.photo_url)
          = label_tag("[item]description", "Description")
          = text_field_tag("[item]description", item.description)
          br
          - if item.url
            = label_tag("[item]url", "URL")
            br
            = text_field_tag("[item]url", item.url)
          = submit_tag
        = link_to "delete", item_path(item.id), confirm: "Are you sure?", method: :delete
    - if current_user
      .add-from-wed
        = form_tag items_path, class: "from-wed" do
          = hidden_field_tag("[item]photo_url", item.photo_url)
          = hidden_field_tag("[item]description", item.description)
          = label_tag "Add to Wedding Plan:"
          = select_tag "[item]wedding_id", options_for_select(@weddings.map{|wedding| [wedding.name, wedding.id]})
          = image_submit_tag 'https://s3.amazonaws.com/bride-items/add.png', class: "add-item"

app/views/weddings/_last_wedding_example.html.slim
.twocol.last
  .wedding-example
    = image_tag wedding.photo_url
    p = link_to wedding.name, user_wedding_path(wedding.user_id, wedding.id)

app/views/weddings/_public_wedding.html.slim
.wedding-bar
  = image_tag wedding.photo_url, style: "height: 175px"
  = link_to wedding.name, wedding_path(wedding.id), class: "title"
  p.time
    = time_ago_in_words(Time.parse(wedding.created_at)) + " ago"
    = " by #{User.find(wedding.user_id).name}"

app/views/weddings/_wedding.html.slim
.wedding-bar
  = image_tag wedding.photo_url, style: "height: 175px"
  = link_to wedding.name, wedding_path(wedding.id), class: "title"
  p.time = time_ago_in_words(Time.parse(wedding.created_at)) + " ago"

app/views/weddings/_wedding_example.html.slim
.twocol
  .wedding-example
    = image_tag wedding.photo_url
    p = link_to wedding.name, user_wedding_path(wedding.user_id, wedding.id)

app/views/weddings/edit.html.slim
= form_tag wedding_path, method: "put" do
  = label_tag("wedding[name]", "Title")
  = text_field_tag("wedding[name]", @wedding.name)
  = label_tag("wedding[description]", "Description")
  = text_field_tag("wedding[description]", @wedding.description)
  = hidden_field_tag("wedding[user_id]", @wedding.user_id)
  = submit_tag

app/views/weddings/index.html.slim
#weddings.bar-list.ninecol
  - if current_user && current_user.id.to_i == params[:user_id].to_i
    h2#tag = "My Wedding Plans"
    br
    = link_to new_wedding_path do
      #plus Add Wedding Plan
  - elsif params[:user_id]
    h2#tag = "#{User.find(params[:user_id]).name}'s Wedding Plans"
  - else
    h1 All Weddings

  - @weddings.each do |wedding|
    = render "public_wedding", { wedding: wedding }
  = will_paginate @weddings

app/views/weddings/index.js.erb
<% @weddings.each do |wedding| %>
  $('#weddings').append('<%= j render("wedding", {wedding: wedding}) %>'); 
  <% if @weddings.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@weddings) %>');
  <% else %>
    $('.pagination').remove();
  <% end %>
<% end %>

app/views/weddings/new.html.slim
.ninecol
  h1 Build a Wedding Plan!
  = form_tag weddings_path do
    = label_tag("[wedding]name", "Title")
    = text_field_tag("[wedding]name")
    = label_tag("[wedding]description", "Description")
    = text_field_tag("[wedding]description")
    = submit_tag

app/views/weddings/show.html.slim
.ninecol
  = render "/weddings/descriptive_wedding", { wedding: @wedding }
  .search-box-list
    - @items.each do |item|
      = render "item", { item: item }
    - if current_user && @wedding.user_id == current_user.id
      = render "/weddings/add_item_bar"